[tool.poetry]
name = "fastapi"
version = "0.1.0"
description = ""
authors = ["Xing gao <738234123@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^2.4.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
